// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQRHCdi6D5jhI5Lr4ISlYVwPJVXt-x3Ms',
    appId: '1:6487545702:web:f2f0a7d2591dfc8ba15aa7',
    messagingSenderId: '6487545702',
    projectId: 'chessafg',
    authDomain: 'chessafg.firebaseapp.com',
    storageBucket: 'chessafg.appspot.com',
    measurementId: 'G-4V4029BXHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMbuNWpKd41e7ajKv2shmLZucN_Wlfj-E',
    appId: '1:6487545702:android:8169c6b1789c6d4ba15aa7',
    messagingSenderId: '6487545702',
    projectId: 'chessafg',
    storageBucket: 'chessafg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-vZ1YVUjBOdOg-9TIpSMvct0behD32xQ',
    appId: '1:6487545702:ios:2c86416711a6d339a15aa7',
    messagingSenderId: '6487545702',
    projectId: 'chessafg',
    storageBucket: 'chessafg.appspot.com',
    iosBundleId: 'com.example.chessafg',
  );
}
