import 'package:chessafg/main_screan/playerData.dart';
import 'package:chessafg/main_screan/playerDetailScreen.dart';
import 'package:flutter/material.dart';
// import 'package:chessafg/player_data.dart';
// import 'player_detail_screen.dart';

class PlayerStatsScreen extends StatefulWidget {
  const PlayerStatsScreen({super.key});

  @override
  State<PlayerStatsScreen> createState() => _PlayerStatsScreenState();
}

class _PlayerStatsScreenState extends State<PlayerStatsScreen> {
  final List<PlayerData> players = [
    PlayerData(
      playerName: 'Habibullah Amini',
      worldRank: 19260,
      title: 'Candidate Master',
      profilePicture: 'assets/images/habib.PNG',
      fideId: 11700777,
      birthYear: 1981,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Candidate Master',
      fideRating: 2047,
      winsBlack: 53,
      losesBlack: 37,
      drawsBlack: 15,
      winsWhite: 50,
      losesWhite: 34,
      drawsWhite: 18,
    ),
    PlayerData(
      playerName: 'S. Wahabuddin Mirzad',
      worldRank: 20571,
      title: 'Fide Master',
      profilePicture: 'assets/images/wahabuddin.PNG',
      fideId: 11700785,
      birthYear: 1987,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Fide Master',
      fideRating: 2035,
      winsBlack: 27,
      losesBlack: 23,
      drawsBlack: 18,
      winsWhite: 29,
      losesWhite: 31,
      drawsWhite: 17,
    ),
    PlayerData(
      playerName: 'Ahmad Safy Kanz',
      worldRank: 28773,
      title: 'Candidate Master',
      profilePicture: 'assets/images/AhmadSafy.PNG',
      fideId: 11700947,
      birthYear: 1997,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Candidate Master',
      fideRating: 1977,
      winsBlack: 24,
      losesBlack: 31,
      drawsBlack: 8,
      winsWhite: 38,
      losesWhite: 17,
      drawsWhite: 5,
    ),
    PlayerData(
      playerName: 'Wais Abdul Khaliq',
      worldRank: 30511,
      title: 'Chess Player',
      profilePicture: 'assets/images/abdulKhaliqWais.PNG',
      fideId: 11700467,
      birthYear: 1988,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Chess Player',
      fideRating: 1968,
      winsBlack: 19,
      losesBlack: 22,
      drawsBlack: 8,
      winsWhite: 25,
      losesWhite: 15,
      drawsWhite: 6,
    ),
    PlayerData(
      playerName: 'Zaheerudden Asefi',
      worldRank: 31736,
      title: 'Chess Player',
      profilePicture: 'assets/images/zaherudin.PNG',
      fideId: 11700467,
      birthYear: 1965,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Chess Player',
      fideRating: 1962,
      winsBlack: 269,
      losesBlack: 327,
      drawsBlack: 33,
      winsWhite: 284,
      losesWhite: 319,
      drawsWhite: 39,
    ),
    PlayerData(
      playerName: 'Basir Ahmad Hotak',
      worldRank: 34611,
      title: 'Chess Player',
      profilePicture: 'assets/images/user.png',
      fideId: 11700467,
      birthYear: 1984,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Chess Player',
      fideRating: 1948,
      winsBlack: 1,
      losesBlack: 2,
      drawsBlack: 2,
      winsWhite: 1,
      losesWhite: 4,
      drawsWhite: 1,
    ),
    PlayerData(
      playerName: 'Abdul Satar',
      worldRank: 34952,
      title: 'Chess Player',
      profilePicture: 'assets/images/user.png',
      fideId: 11700467,
      birthYear: 1993,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Chess Player',
      fideRating: 1947,
      winsBlack: 6,
      losesBlack: 11,
      drawsBlack: 2,
      winsWhite: 11,
      losesWhite: 9,
      drawsWhite: 4,
    ),
    PlayerData(
      playerName: 'Homayoun Mohtaat',
      worldRank: 36644,
      title: 'Chess Player',
      profilePicture: 'assets/images/Homayoun.PNG',
      fideId: 11700467,
      birthYear: 1972,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Chess Player',
      fideRating: 1939,
      winsBlack: 89,
      losesBlack: 93,
      drawsBlack: 16,
      winsWhite: 79,
      losesWhite: 88,
      drawsWhite: 18,
    ),
    PlayerData(
      playerName: 'Sepehr Sakhawaty',
      worldRank: 38970,
      title: 'Chess Player',
      profilePicture: 'assets/images/sepehr.PNG',
      fideId: 11700467,
      birthYear: 2003,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Chess Player',
      fideRating: 1929,
      winsBlack: 69,
      losesBlack: 89,
      drawsBlack: 15,
      winsWhite: 81,
      losesWhite: 72,
      drawsWhite: 15,
    ),
    PlayerData(
      playerName: 'Aminullah Khairandish',
      worldRank: 39149,
      title: 'Chess Player',
      profilePicture: 'assets/images/user.png',
      fideId: 11700467,
      birthYear: 1976,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Chess Player',
      fideRating: 1928,
      winsBlack: 6,
      losesBlack: 4,
      drawsBlack: 3,
      winsWhite: 9,
      losesWhite: 4,
      drawsWhite: 1,
    ),
    PlayerData(
      playerName: 'Hamidullah Sarwari',
      worldRank: 30511,
      title: 'Chess Player',
      profilePicture: 'assets/images/hamidullah.PNG',
      fideId: 11700467,
      birthYear: 1989,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Chess Player',
      fideRating: 1923,
      winsBlack: 50,
      losesBlack: 53,
      drawsBlack: 22,
      winsWhite: 47,
      losesWhite: 52,
      drawsWhite: 20,
    ),
    PlayerData(
      playerName: 'Saifudin Ayoubi',
      worldRank: 42316,
      title: 'Chess Player',
      profilePicture: 'assets/images/user.png',
      fideId: 11700467,
      birthYear: 1991,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Chess Player',
      fideRating: 1914,
      winsBlack: 2,
      losesBlack: 3,
      drawsBlack: 4,
      winsWhite: 2,
      losesWhite: 6,
      drawsWhite: 3,
    ),
    PlayerData(
      playerName: 'Khusraw Farzad',
      worldRank: 30511,
      title: 'Chess Player',
      profilePicture: 'assets/images/user.png',
      fideId: 11700467,
      birthYear: 44514,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Chess Player',
      fideRating: 1905,
      winsBlack: 29,
      losesBlack: 24,
      drawsBlack: 7,
      winsWhite: 35,
      losesWhite: 19,
      drawsWhite: 9,
    ),
    PlayerData(
      playerName: 'Fahim Sharifi',
      worldRank: 30511,
      title: 'Chess Player',
      profilePicture: 'assets/images/user.png',
      fideId: 11700467,
      birthYear: 1994,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Chess Player',
      fideRating: 1900,
      winsBlack: 2,
      losesBlack: 1,
      drawsBlack: 2,
      winsWhite: 4,
      losesWhite: 2,
      drawsWhite: 0,
    ),
    PlayerData(
      playerName: 'Sayed Qasem Sadat',
      worldRank: 50292,
      title: 'Chess Player',
      profilePicture: 'assets/images/user.png',
      fideId: 11700467,
      birthYear: 1971,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Chess Player',
      fideRating: 1882,
      winsBlack: 0,
      losesBlack: 4,
      drawsBlack: 1,
      winsWhite: 0,
      losesWhite: 3,
      drawsWhite: 1,
    ),
    PlayerData(
      playerName: 'Allah dad Asadi',
      worldRank: 52000,
      title: 'Chess Player',
      profilePicture: 'assets/images/user.png',
      fideId: 11700467,
      birthYear: 1985,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Chess Player',
      fideRating: 1875,
      winsBlack: 7,
      losesBlack: 5,
      drawsBlack: 1,
      winsWhite: 11,
      losesWhite: 1,
      drawsWhite: 2,
    ),
    PlayerData(
      playerName: 'Asef Rahmani',
      worldRank: 53723,
      title: 'Chess Player',
      profilePicture: 'assets/images/user.png',
      fideId: 11700467,
      birthYear: 1973,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Chess Player',
      fideRating: 1869,
      winsBlack: 354,
      losesBlack: 173,
      drawsBlack: 55,
      winsWhite: 358,
      losesWhite: 186,
      drawsWhite: 60,
    ),
    PlayerData(
      playerName: 'Jarullah Badghisi',
      worldRank: 56928,
      title: 'Chess Player',
      profilePicture: 'assets/images/user.png',
      fideId: 11700467,
      birthYear: 1998,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Chess Player',
      fideRating: 1856,
      winsBlack: 42,
      losesBlack: 24,
      drawsBlack: 9,
      winsWhite: 38,
      losesWhite: 30,
      drawsWhite: 8,
    ),
    PlayerData(
      playerName: 'Wais Ahmad',
      worldRank: 62200,
      title: 'Chess Player',
      profilePicture: 'assets/images/waisNaderi.PNG',
      fideId: 11700467,
      birthYear: 2000,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Chess Player',
      fideRating: 1837,
      winsBlack: 12,
      losesBlack: 10,
      drawsBlack: 1,
      winsWhite: 14,
      losesWhite: 5,
      drawsWhite: 5,
    ),
    PlayerData(
      playerName: 'Mahmood Aamanzai',
      worldRank: 66435,
      title: 'Chess Player',
      profilePicture: 'assets/images/user.png',
      fideId: 11700467,
      birthYear: 1983,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Chess Player',
      fideRating: 1821,
      winsBlack: 4,
      losesBlack: 1,
      drawsBlack: 0,
      winsWhite: 2,
      losesWhite: 3,
      drawsWhite: 1,
    ),
    PlayerData(
      playerName: 'Shekib Rahmani',
      worldRank: 69234,
      title: 'Chess Player',
      profilePicture: 'assets/images/user.png',
      fideId: 11700467,
      birthYear: 1998,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Chess Player',
      fideRating: 1811,
      winsBlack: 1,
      losesBlack: 2,
      drawsBlack: 1,
      winsWhite: 3,
      losesWhite: 2,
      drawsWhite: 0,
    ),
    PlayerData(
      playerName: 'Sayed Ahmad Agha Hashemi',
      worldRank: 73964,
      title: 'Chess Player',
      profilePicture: 'assets/images/user.png',
      fideId: 11700467,
      birthYear: 1979,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Chess Player',
      fideRating: 1794,
      winsBlack: 9,
      losesBlack: 7,
      drawsBlack: 2,
      winsWhite: 11,
      losesWhite: 5,
      drawsWhite: 2,
    ),
    PlayerData(
      playerName: 'Murtaza Yusufi',
      worldRank: 75433,
      title: 'Grand Master',
      profilePicture: 'assets/images/murtaza.jpg',
      fideId: 1170962,
      birthYear: 2002,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Grand Master',
      fideRating: 1789,
      winsBlack: 4,
      losesBlack: 0,
      drawsBlack: 1,
      winsWhite: 2,
      losesWhite: 3,
      drawsWhite: 1,
    ),
    PlayerData(
      playerName: 'Ahmad Shaker Jamal',
      worldRank: 75434,
      title: 'Grand Master',
      profilePicture: 'assets/images/user.png',
      fideId: 1170966,
      birthYear: 2002,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Grand Master',
      fideRating: 1788,
      winsBlack: 13,
      losesBlack: 10,
      drawsBlack: 6,
      winsWhite: 12,
      losesWhite: 32,
      drawsWhite: 11,
    ),
    PlayerData(
      playerName: 'Mohammad Esmail',
      worldRank: 75770,
      title: 'Chess Player',
      profilePicture: 'assets/images/user.png',
      fideId: 11700467,
      birthYear: 2002,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Chess Player',
      fideRating: 1788,
      winsBlack: 1,
      losesBlack: 4,
      drawsBlack: 0,
      winsWhite: 2,
      losesWhite: 1,
      drawsWhite: 2,
    ),
    PlayerData(
      playerName: 'Mohammad Naser Sharifi',
      worldRank: 81748,
      title: 'Chess Player',
      profilePicture: 'assets/images/naserSharifi.PNG',
      fideId: 11700467,
      birthYear: 1993,
      sex: 'Male',
      federation: 'Afghanistan',
      fideTitle: 'Chess Player',
      fideRating: 1767,
      winsBlack: 1,
      losesBlack: 3,
      drawsBlack: 1,
      winsWhite: 4,
      losesWhite: 1,
      drawsWhite: 1,
    ),
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.orange,
        title: const Text('AFG National Players'),
      ),
      body: ListView.builder(
        itemCount: players.length,
        itemBuilder: (context, index) {
          return Card(
            margin: const EdgeInsets.all(10),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(15),
            ),
            child: ListTile(
              leading: CircleAvatar(
                backgroundImage: AssetImage(players[index].profilePicture),
              ),
              title: Text('${index + 1}. ${players[index].playerName}'),
              // ignore: unnecessary_string_interpolations
              subtitle: Text('${players[index].title}'),
              onTap: () {
                Navigator.push(
                  context,
                  MaterialPageRoute(
                    builder: (context) =>
                        PlayerDetailScreen(player: players[index]),
                  ),
                );
              },
            ),
          );
        },
      ),
    );
  }
}